{
 "title": "Dashboard Monitoring All Server Overview",
 "description": "Just like https://grafana.com/grafana/dashboards/1860-node-exporter-full/ This dashboard will visualise all servers in the same panel",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(node_uname_info, project)"
    }
   },
   {
    "name": "job",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{project=~\"$project\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Linux",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0",
     "legendFormat": "hostname"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)",
     "legendFormat": "running time"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0",
     "legendFormat": "total memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "Total number of cores"
    },
    {
     "expr": "node_load5{job=~\"$job\"}",
     "legendFormat": "5 minutes load"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU Usage rate"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100 or ((node_memory_MemTotal_bytes{job=~\"$job\"}-node_memory_MemFree_bytes{job=~\"$job\"}-node_memory_Buffers_bytes{job=~\"$job\"}-node_memory_Cached_bytes{job=~\"$job\"}) / node_memory_MemTotal_bytes{job=~\"$job\"}) *100",
     "legendFormat": "memory usage"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Partition usage"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{job=~\"$job\"}[5m])) by (instance)",
     "legendFormat": "maximum read"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{job=~\"$job\"}[5m])) by (instance)",
     "legendFormat": "maximum write"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"$job\"}[5m])*8) by (instance)",
     "legendFormat": "Download bandwidth"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=~\"$job\"}[5m])*8) by (instance)",
     "legendFormat": "Upload bandwidth"
    }
   ]
  },
  {
   "title": "$job：Overall total load vs. overall average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\", mode='system'})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum(node_load5{job=~\"$job\"})",
     "legendFormat": "Total 5 Minute Load"
    },
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "Total Average Utilization"
    }
   ]
  },
  {
   "title": "$job：Overall total memory vs. overall average memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{job=~\"$job\"}))*100",
     "legendFormat": "Total Average uUilization"
    }
   ]
  },
  {
   "title": "$job：Overall Total Disk vs. Overall Average Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total Disk Volume"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "Total Average Utilization"
    }
   ]
  }
 ]
}