{
 "title": "NGINX Performance Monitor",
 "description": "Dashboard for NGINX Prometheus exporter by ThanhNV",
 "tags": [
  "nginx",
  "prometheus",
  "nginx_exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(nginx_up,job)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nginx_up{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NGINX Status for $host",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{job=\"$job\", instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{job=\"$job\", instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{job=\"$job\", instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{job=\"$job\", instance=~\"$host\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{job=\"$job\", instance=~\"$host\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{job=\"$job\", instance=~\"$host\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{job=\"$job\", instance=~\"$host\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{job=\"$job\", instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}