global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'zns monitoring'

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "node-exporter.rules"
  - "prometheus-self-monitoring.rules"
  - "nginx-exporter.rules"
  - "rabbitmq_alerts.rules"
  - "mysql-exporter.rules"

scrape_configs:
  - job_name: 'ZNS-API'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.92.6.1:9100', '10.92.6.2:9100', '10.92.6.3:9100', '10.92.6.4:9100', '10.92.6.5:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-Worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.92.10.101:9100', '10.92.10.102:9100', '10.92.10.103:9100', '10.92.10.104:9100', '10.92.10.105:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-DLR'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['10.92.6.21:9100', '10.92.6.22:9100', '10.92.6.23:9100', '10.92.6.24:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-RabbitMQ'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.92.6.31:9100', '10.92.6.32:9100', '10.92.6.33:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-Redis'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.92.10.31:9100', '10.92.10.32:9100', '10.92.10.33:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-Database'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.92.10.1:9100', '10.92.10.2:9100', '10.92.10.3:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-ISC'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.92.6.28:9100', '10.92.6.29:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-SMPP'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.92.6.112:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-HA-INT'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.92.10.28:9100', '10.92.10.29:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance      

  - job_name: 'ZNS-HA-EXT'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.92.6.8:9100', '10.92.6.9:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance   

  - job_name: 'ZNS-Portal'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.92.6.101:9100', '10.92.6.102:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'ZNS-Jobs'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.92.10.100:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'Nginx-API'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.92.6.1:9113', '10.92.6.2:9113', '10.92.6.3:9113', '10.92.6.4:9113', '10.92.6.5:9113']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'Nginx-DLR'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.92.6.21:9113', '10.92.6.22:9113', '10.92.6.23:9113', '10.92.6.24:9113']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'Nginx-Portal'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.92.6.101:9113','10.92.6.102:9113']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'RabbitMQ-01'
    static_configs:
      - targets: ['10.92.6.31:15692']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'RabbitMQ-02'
    static_configs:
      - targets: ['10.92.6.32:15692']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'RabbitMQ-03'
    static_configs:
      - targets: ['10.92.6.33:15692']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'Mysql-DB'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.92.10.1:9104','10.92.10.2:9104','10.92.10.3:9104']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'checkpoint-prod'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /snmp
    params:
      module: [if_mib]
      auth: [public_v2]
    static_configs:
      - targets: ['10.92.6.252']
        labels:
          display: 'ZNS-CP-GW-2_10.92.6.252'        
      - targets: ['10.92.6.253']
        labels:
          display: 'ZNS-CP-GW-1_10.92.6.253'
      - targets: ['10.151.90.235']
        labels:
          display: 'ZNS-CP-SMS_10.151.90.235'     
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [display]
        target_label: instance
      - source_labels: [__param_target]
        target_label: snmp_target          
      - target_label: __address__
        replacement: 10.92.6.112:9116
        
  - job_name: 'redis'
    metrics_path: /scrape
    static_configs:
      - targets:
        - 'redis://10.92.10.31:6379'
        - 'redis://10.92.10.32:6379'
        - 'redis://10.92.10.33:6379'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: redis-exporter:9121
      - source_labels: [__param_target]
        target_label: instance          
