global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'zns monitoring'

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "node-exporter.rules"
  - "prometheus-self-monitoring.rules"
  - "nginx-exporter.rules"

scrape_configs:
  - job_name: 'ZNS-API'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.18.1.11:9100', '172.18.1.12:9100', '172.18.1.13:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance      

  - job_name: 'ZNS-Worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.1.31:9100', '172.18.1.32:9100', '172.18.1.33:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance       

  - job_name: 'ZNS-DLR'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['172.18.1.41:9100', '172.18.1.42:9100', '172.18.1.43:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance       

  - job_name: 'ZNS-Queue'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.18.1.51:9100', '172.18.1.52:9100', '172.18.1.53:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance       

  - job_name: 'ZNS-Database'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.1.1:9100', '172.18.1.2:9100', '172.18.1.3:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance       

  - job_name: 'ZNS-Jobs'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.1.100:9100']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance    

  - job_name: 'Nginx-API'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.18.1.11:9113','172.18.1.12:9113','172.18.1.13:9113']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'Nginx-DLR'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.18.1.41:9113','172.18.1.42:9113','172.18.1.43:9113']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance

  - job_name: 'Nginx-Portal'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.18.1.21:9113','172.18.1.22:9113']
    relabel_configs:
    - source_labels: [__address__]
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance
